var res = {
    map_background_0000_png: "res/Art/map/map_background_0000.png",
    map_background_png: "res/Art/map/map_background.png",
    map_background_0001_png: "res/Art/map/map_background_0001.png",
    map_background_0002_png: "res/Art/map/map_background_0002.png",
    map_background_0003_png: "res/Art/map/map_background_0003.png",
    map_cell_0002_png: "res/Art/map/map_cell_0002.png",
    map_cell_0003_png: "res/Art/map/map_cell_0003.png",
    map_forest_obstacle_2_png: "res/Art/map/map_forest_obstacle_2.png",
    map_hole_0000_png: "res/Art/map/map_hole_0000.png",
    map_river_0000_png: "res/Art/map/map_river_0000.png",
    ui_grid_png: "res/Art/UI New/ui_grid.png",
    map_monster_gate_player_png: "res/Art/map/map_monster_gate_player.png",
    map_monster_gate_enemy_png: "res/Art/map/map_monster_gate_enemy.png",
    map_decoration_0001_png: "res/Art/map/map_decoration_0001.png",
    map_decoration_0002_png: "res/Art/map/map_decoration_0002.png",
    map_house_png: "res/Art/map/map_house.png",
    common_icon_trophy_small_png: "res/Art/common/common_icon_trophy_small.png",
    common_icon_house_png: "res/Art/common/common_icon_house.png",
    battle_item_attack_speed_png: "res/Art/battle/battle_item_attack_speed.png",
    battle_item_damage_png: "res/Art/battle/battle_item_damage.png",
    battle_item_range_png: "res/Art/battle/battle_item_range.png",
    ui_hole_png: "res/Art/UI New/ui_hole.png",
    ui_icon_arrow_png: "res/Art/UI New/ui_icon_arrow.png",

    fx_result_win_json: "res/Art/battle/battle_result/fx/fx_result_win.json",
    fx_result_win_atlas: "res/Art/battle/battle_result/fx/fx_result_win.atlas",
    fx_result_lose_json: "res/Art/battle/battle_result/fx/fx_result_lose.json",
    fx_result_draw_json: "res/Art/battle/battle_result/fx/fx_result_draw.json",
    fx_result_lose_atlas: "res/Art/battle/battle_result/fx/fx_result_lose.atlas",
    fx_result_draw_atlas: "res/Art/battle/battle_result/fx/fx_result_draw.atlas",

    battle_result_avatar_border_loser_png: "res/Art/battle/battle_result/battle_result_avatar_border_loser.png",
    common_avatar_png: "res/Art/common/common_avatar.png",
    common_avatar_border_png: "res/Art/common/common_avatar_border.png",
    battle_result_icon_swords_lose_png: "res/Art/battle/battle_result/battle_result_icon_swords_lose.png",
    battle_result_icon_swords_win_png: "res/Art/battle/battle_result/battle_result_icon_swords_win.png",
    battle_result_line_lose_png: "res/Art/battle/battle_result/battle_result_line_lose.png",
    battle_result_line_win_png: "res/Art/battle/battle_result/battle_result_line_win.png",

    battle_target_hp_png: "res/Art/battle/battle_target_hp.png",
    battle_target_hp_background_png: "res/Art/battle/battle_target_hp_background.png",
    effect_stun_json: "res/Art/tower/fx/effect_stun.json",
    effect_stun_atlas: "res/Art/tower/fx/effect_stun.atlas",
    tower_strength_fx_json: "res/Art/tower/fx/tower_strength_fx.json",
    tower_strength_fx_atlas: "res/Art/tower/fx/tower_strength_fx.atlas",


    SVN_Supercell_Magic_ttf: "res/Art/font/SVN-Supercell Magic.ttf",

    lobby_ui: 'res/MainScene.json',
    lobby_bg : 'res/lobby_background.png',
    lobby_login_btn: 'res/login_button.png',
    lobby_login_input: 'res/login_input.png',
    lobby_page_btn: 'res/lobby_page_btn.png',
    lobby_page_btn_selecting: 'res/lobby_page_btn_selecting.png',
    lobby_page_card: 'res/lobby_page_icon_cards.png',
    lobby_page_clan: 'res/lobby_page_icon_clan.png',
    lobby_page_home: 'res/lobby_page_icon_home.png',
    lobby_page_shop: 'res/lobby_page_icon_shop.png',
    lobby_page_social: 'res/lobby_page_icon_social.png',
    lobby_home_treasure_empty: 'res/lobby/lobby_home_treasure_empty.png',
    lobby_home_treasure_finished: 'res/lobby/lobby_home_treasure_finished.png',
    lobby_home_treasure_opening: 'res/lobby/lobby_home_treasure_opening.png',
    lobby_battle_btn: 'res/lobby_home_btn_battle.png',
    lobby_battle_btn_pressing: 'res/lobby_home_btn_battle_pressing.png',
    lobby_battle_btn_label: 'res/lobby_home_btn_battle_txt.png',
    common_icon_g: 'res/common_icon_g.png',
    common_icon_gold: 'res/common_icon_gold.png',
    common_icon_trophy: 'res/common_icon_trophy.png',
    lobby_currency_bg: 'res/lobby_currency_background.png',
    lobby_player_bg: 'res/lobby_home_player.png',
    lobby_rank_bg: 'res/lobby_box.png',
    lobby_gold_bg: 'res/common_notification_bar.png',
    card_border: 'res/card/card_border_1.png',
    card_background: 'res/card/card_background_3.png',
    card_lv: 'res/card/card_level.png',
    card_tower_cannon: 'res/card/card_tower_cannon.png',
    card_tower_wizard: 'res/card/card_tower_wizard.png',
    card_tower_boomerang: 'res/card/card_tower_boomerang.png',
    card_tower_oil_gun: 'res/card/card_tower_oil_gun.png',
    card_tower_ice_gun: 'res/card/card_tower_ice_gun.png',
    card_tower_attack_speed: 'res/card/card_tower_attack_speed.png',
    card_tower_damage: 'res/card/card_tower_damage.png',
    card_potion_fireball: 'res/card/card_potion_fireball.png',
    card_potion_frozen: 'res/card/card_potion_frozen.png',
    card_potion_heal: 'res/card/card_potion_heal.png',
    card_potion_speed_up: 'res/card/card_potion_speed_up.png',
    card_monster_swordsman: 'res/card/card_monster_swordsman.png',
    card_monster_assassin: 'res/card/card_monster_assassin.png',
    card_monster_giant: 'res/card/card_monster_giant.png',
    card_monster_bat: 'res/card/card_monster_bat.png',
    card_monster_ninja: 'res/card/card_monster_ninja.png',
    miniature_tower_cannon_1: 'res/card/miniature_tower_cannon_1.png',
    miniature_tower_cannon_2: 'res/card/miniature_tower_cannon_2.png',
    miniature_tower_cannon_3: 'res/card/miniature_tower_cannon_3.png',
    miniature_tower_wizard_1: 'res/card/miniature_tower_wizard_1.png',
    miniature_tower_wizard_2: 'res/card/miniature_tower_wizard_2.png',
    miniature_tower_wizard_3: 'res/card/miniature_tower_wizard_3.png',
    miniature_tower_boomerang_1: 'res/card/miniature_tower_boomerang_1.png',
    miniature_tower_boomerang_2: 'res/card/miniature_tower_boomerang_2.png',
    miniature_tower_boomerang_3: 'res/card/miniature_tower_boomerang_3.png',
    miniature_tower_oil_gun_1: 'res/card/miniature_tower_oil_gun_1.png',
    miniature_tower_oil_gun_2: 'res/card/miniature_tower_oil_gun_2.png',
    miniature_tower_oil_gun_3: 'res/card/miniature_tower_oil_gun_3.png',
    miniature_tower_ice_gun_1: 'res/card/miniature_tower_ice_gun_1.png',
    miniature_tower_ice_gun_2: 'res/card/miniature_tower_ice_gun_2.png',
    miniature_tower_ice_gun_3: 'res/card/miniature_tower_ice_gun_3.png',
    miniature_tower_attack_speed_1: 'res/card/miniature_tower_attack_speed_1.png',
    miniature_tower_attack_speed_2: 'res/card/miniature_tower_attack_speed_2.png',
    miniature_tower_attack_speed_3: 'res/card/miniature_tower_attack_speed_3.png',
    miniature_tower_damage_1: 'res/card/miniature_tower_damage_1.png',
    miniature_tower_damage_2: 'res/card/miniature_tower_damage_2.png',
    miniature_tower_damage_3: 'res/card/miniature_tower_damage_3.png',
    miniature_monster_swordsman: 'res/card/miniature_monster_swordsman.png',
    miniature_monster_assassin: 'res/card/miniature_monster_assassin.png',
    miniature_monster_giant: 'res/card/miniature_monster_giant.png',
    miniature_monster_bat: 'res/card/miniature_monster_bat.png',
    miniature_monster_ninja: 'res/card/miniature_monster_ninja.png'
};