var TowerType = [
    {},

    {
        type: MW.TOWER.TYPE.COMBAT,
        target: MW.TOWER.TARGET.BOTH,
        dameType: MW.TOWER.DAME_TYPE.SINGLE,
        bulletType: MW.TOWER.BULLET_TYPE.LOCK_MONSTER,
        energy: 8,
        impactType: MW.IMPACT.DAME,
        impactNumber: [10.0, 15.0, 30.0],
        shootSpeed: [0.6, 0.5, 0.4],
        distance: [1.5, 1.7, 2],
        bulletDistance: [0, 0, 0],
        bulletSpeed: [50, 50, 50],
        buildTime: MW.TOWER.BUILD_TIME.DEFAULT,
        path: [
            "res/Art/tower/frame/cannon_1_2/tower_cannon",
            "res/Art/tower/frame/cannon_1_2/tower_cannon_idle",
            "res/Art/tower/frame/cannon_1_2/tower_cannon_attack",
        ],
        bulletLink: "res/Art/tower/frame/cannon_1_2/tower_cannon_bullet_0000.png",
        name: "Pháo cú",
        numOfFrames: [0, 80, 134],
        stunDuration: 0.2,
        animAttack: [
            {from: 72, to: 80},
            {from: 0, to: 8},
            {from: 36, to: 44},
            {from: 36, to: 44},
            {from: 9, to: 17},
            {from: 9, to: 17},
            {from: 54, to: 62},
            {from: 54, to: 62},
        ],

        animIdle: [
            {from: 120, to: 134},
            {from: 0, to: 14},
            {from: 60, to: 74},
            {from: 60, to: 74},
            {from: 15, to: 29},
            {from: 15, to: 29},
            {from: 90, to: 104},
            {from: 90, to: 104},
        ]
    },

    {
        type: MW.TOWER.TYPE.COMBAT,
        target: MW.TOWER.TARGET.GROUND,
        dameType: MW.TOWER.DAME_TYPE.MULTI,
        bulletType: MW.TOWER.BULLET_TYPE.LOCK_POSITION,
        energy: 12,
        impactType: MW.IMPACT.DAME,
        impactNumber: [5, 8, 20],
        shootSpeed: [2.2, 2, 1.8],
        distance: [1.5, 1.7, 2],
        bulletDistance: [1, 1, 1],
        bulletSpeed: [30, 30, 30],
        buildTime: MW.TOWER.BUILD_TIME.DEFAULT,
        path: [
            "res/Art/tower/frame/wizard_1_2/tower_wizard",
            "res/Art/tower/frame/wizard_1_2/tower_wizard_idle",
            "res/Art/tower/frame/wizard_1_2/tower_wizard_attack",
        ],
        bulletLink: "res/Art/tower/frame/wizard_1_2/tower_wizard_bullet_0000.png",
        name: "Quạ pháp sư",
        numOfFrames: [0, 80, 134],
        damageBuff: 10,
        animAttack: [
            {from: 72, to: 80},
            {from: 0, to: 8},
            {from: 36, to: 44},
            {from: 36, to: 44},
            {from: 9, to: 17},
            {from: 9, to: 17},
            {from: 54, to: 62},
            {from: 54, to: 62},
        ],

        animIdle: [
            {from: 120, to: 134},
            {from: 0, to: 14},
            {from: 60, to: 74},
            {from: 60, to: 74},
            {from: 30, to: 44},
            {from: 30, to: 44},
            {from: 90, to: 104},
            {from: 90, to: 104},
        ]
    },

    {
        type: MW.TOWER.TYPE.COMBAT,
        target: MW.TOWER.TARGET.BOTH,
        dameType: MW.TOWER.DAME_TYPE.MULTI,
        bulletType: MW.TOWER.BULLET_TYPE.LOCK_POSITION,
        energy: 10,
        impactType: MW.IMPACT.DAME,
        impactNumber: [3, 5, 8],
        shootSpeed: [1.5, 1.3, 1.0],
        distance: [2, 2.3, 2.8],
        bulletDistance: [0, 0, 0],
        bulletSpeed: [30, 30, 30],
        buildTime: MW.TOWER.BUILD_TIME.DEFAULT,
        path: [
            "res/Art/tower/frame/boomerang_1_2/tower_boomerang",
            "res/Art/tower/frame/boomerang_1_2/tower_boomerang_idle",
            "res/Art/tower/frame/boomerang_1_2/tower_boomerang_attack",
        ],
        bulletLink: "res/Art/tower/frame/boomerang_1_2/tower_boomerang_bullet_1_0000.png",
        name: "Ếch đồ tể",
        numOfFrames: [0, 98, 125],
        damageIncreaseRate: 50,
        animAttack: [
            {from: 88, to: 98},
            {from: 0, to: 10},
            {from: 44, to: 54},
            {from: 44, to: 54},
            {from: 11, to: 21},
            {from: 11, to: 21},
            {from: 66, to: 76},
            {from: 66, to: 76},
        ],

        animIdle: [
            {from: 112, to: 125},
            {from: 0, to: 13},
            {from: 56, to: 69},
            {from: 56, to: 69},
            {from: 14, to: 27},
            {from: 14, to: 27},
            {from: 84, to: 97},
            {from: 84, to: 97},
        ]
    },

    {
        type: MW.TOWER.TYPE.MAGIC,
        target: MW.TOWER.TARGET.GROUND,
        dameType: MW.TOWER.DAME_TYPE.SINGLE,
        bulletType: MW.TOWER.BULLET_TYPE.LOCK_MONSTER,
        energy: 10,
        impactType: MW.IMPACT.FROZEN,
        impactNumber: [1.5, 1.5, 1.5],
        shootSpeed: [3.4, 3.2, 3.0],
        distance: [1.8, 2.0, 2.2],
        bulletDistance: [0, 0, 0],
        bulletSpeed: [60, 60, 60],
        buildTime: MW.TOWER.BUILD_TIME.DEFAULT,
        path: [
            "res/Art/tower/frame/ice_gun",
            "res/Art/tower/frame/ice_gun/tower_ice_gun_idle",
            "res/Art/tower/frame/ice_gun/tower_ice_gun_attack",
        ],
        bulletLink: "res/Art/tower/frame/ice_gun/tower_ice_gun_bullet_0000.png",
        name: "Gấu Bắc Cực",
        numOfFrames: [0, 89, 125],
        damageIncreaseRate: 50,

        animAttack: [
            {from: 80, to: 89},
            {from: 0, to: 9},
            {from: 40, to: 49},
            {from: 40, to: 49},
            {from: 10, to: 19},
            {from: 10, to: 19},
            {from: 60, to: 69},
            {from: 60, to: 69},
        ],

        animIdle: [
            {from: 112, to: 125},
            {from: 0, to: 13},
            {from: 56, to: 69},
            {from: 56, to: 69},
            {from: 14, to: 27},
            {from: 14, to: 27},
            {from: 84, to: 97},
            {from: 84, to: 97},
        ]
    },

    {
        type: MW.TOWER.TYPE.SUPPORT,
        target: MW.TOWER.TARGET.TOWER,
        dameType: null,
        bulletType: null,
        energy: 12,
        impactType: MW.IMPACT.BUFF,
        impactNumber: [20, 25, 35],
        shootSpeed: [0, 0, 0],
        distance: [1.2, 1.8, 2.5],
        bulletDistance: [0, 0, 0],
        bulletSpeed: [0, 0, 0],
        buildTime: MW.TOWER.BUILD_TIME.DEFAULT,
        path: [
            "res/Art/tower/frame/damage/tower_damage",
            "res/Art/tower/frame/damage/tower_damage_idle",
            "res/Art/tower/frame/damage/tower_damage_attack",
        ],
        bulletLink: "",
        numOfFrames: [0, 80, 134],
        name: "Dê phát động"
    },
    

]